apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scorpion.fullname" . }}-secrets
  labels:
    {{- include "scorpion.labels" . | nindent 4 }}
type: Opaque
stringData:
  SCORPION_AUTH_TOKEN_SECRET:   {{ .Values.secrets.tokenSecret | quote }}
  SCORPION_AUTH_TICKET_SECRET:  {{ .Values.secrets.ticketSecret | quote }}
  SCORPION_REPOSITORY_PASSWORD: {{ .Values.secrets.redisPassword | quote }}

